const COMPONENT_PAGES = {
  'component_buttons.html': ['3.1.1', '按钮', 'Buttons', '触发即时操作或提交明确指令。按钮文案应描述动作结果，并以层级区分主次操作。', 'Trigger immediate actions or submit explicit commands. Labels describe outcomes; hierarchy separates primary and secondary actions.'],
  'component_switch.html': ['3.1.2', '开关', 'Switch / Toggle', '用于立即生效的二元状态切换。标签描述被控制的对象，而不是重复“开 / 关”。', 'Use for binary settings that take effect immediately. Label the controlled setting instead of repeating “on / off”.'],
  'component_radio_button.html': ['3.2.1', '单选按钮', 'Radio Button', '用于从一组互斥选项中选择一项。选项应始终成组出现，并默认提供合理选择。', 'Use to select one option from a mutually exclusive group. Always show the group and provide a sensible default.'],
  'component_checkbox.html': ['3.2.2', '复选框', 'Checkbox', '用于独立选项或多项选择。每个选项都应能独立理解，不用复选框触发即时动作。', 'Use for independent choices or multi-select. Each option must stand alone; do not use checkboxes as action triggers.'],
  'component_slider.html': ['3.3.3', '调控', 'Control', '用于在连续或分段范围内快速调节数值。关键数值应同步显示，并允许精确输入。', 'Use for quick adjustment across a continuous or stepped range. Show the value and provide precise input when needed.'],
  'component_stepper.html': ['3.4.6', '步骤条', 'Steps', '用于呈现多步骤任务的当前位置、已完成步骤与后续路径，帮助用户理解整体进度。', 'Shows the current, completed, and upcoming stages of a multi-step task so users understand overall progress.'],
  'component_wheel_picker.html': ['3.2.3', '滚轮选择器', 'Wheel Picker', '用于触控设备上的连续候选值选择。当前值保持居中突出，并提供清晰的确认方式。', 'Use for continuous value selection on touch devices. Keep the current value centered and provide clear confirmation.'],
  'component_text_field.html': ['3.3.1', '文本框', 'Text Field', '用于输入或编辑文本。标签持续可见，错误信息说明原因并给出修正路径。', 'Use to enter or edit text. Keep labels visible and make errors explain both cause and recovery.'],
  'component_dropdown_select.html': ['3.3.2', '下拉选择', 'Dropdown / Select', '用于从较长的预定义列表中选择一项。短列表优先直接展示，避免隐藏必要选项。', 'Use to choose one value from a longer predefined list. Show short lists directly instead of hiding essential choices.'],
  'component_app_bar.html': ['3.4.1', '应用栏', 'App Bar', '承载页面层级、标题与高频操作。滚动和跨状态变化时保持结构稳定。', 'Carries page hierarchy, title, and frequent actions. Keep its structure stable across scrolling and state changes.'],
  'component_navigation.html': ['3.4.2', '导航', 'Navigation', '帮助用户在主要任务或信息区域间切换。位置、顺序和当前状态应跨页面保持一致。', 'Moves users between primary tasks or information areas. Preserve placement, order, and current-state cues across pages.'],
  'component_tabs.html': ['3.4.3', '标签页', 'Tabs', '用于同层级内容之间切换。标签保持简短，数量过多时改用更合适的导航模式。', 'Switches between peer content sections. Keep labels short and choose another navigation pattern when tabs become crowded.'],
  'component_breadcrumbs.html': ['3.4.4', '面包屑', 'Breadcrumbs', '显示当前位置及其上级路径，适用于三层及以上的信息结构。当前页不可点击。', 'Shows the current location and its parent path in structures three levels or deeper. The current page is not interactive.'],
  'component_pagination.html': ['3.4.5', '分页', 'Pagination', '将较长结果集分成稳定页面。保留当前位置，并在筛选变化后给出可预期的重置行为。', 'Splits long result sets into stable pages. Preserve position and reset predictably when filters change.'],
  'component_card.html': ['3.5.1', '卡片', 'Card', '将相关内容与操作组织为一个可识别单元。卡片层级不应替代清晰的信息架构。', 'Groups related content and actions into a recognizable unit. Card layers do not replace clear information architecture.'],
  'component_list_tile.html': ['3.5.2', '列表 / 列表项', 'List / List Tile', '以一致结构呈现可扫描的信息集合。主信息、辅助信息和操作保持稳定对齐。', 'Presents scannable collections with a consistent structure. Align primary content, supporting content, and actions predictably.'],
  'component_avatar.html': ['3.5.3', '头像', 'Avatar', '代表用户、家庭或设备身份。图片不可用时使用稳定的文字或图标占位。', 'Represents a person, household, or device identity. Use a stable text or icon fallback when imagery is unavailable.'],
  'component_divider.html': ['3.5.4', '分割线', 'Divider', '用于区分相邻内容组，不承担主要层级表达。优先通过间距建立关系，仅在必要时使用。', 'Separates adjacent content groups without carrying primary hierarchy. Prefer spacing and add dividers only when needed.'],
  'component_badge.html': ['3.5.5', '徽标', 'Badge', '以紧凑形式表达计数或短状态。内容应简短，不将关键告警仅依赖颜色表达。', 'Expresses a count or short status compactly. Keep content brief and never communicate critical alerts by color alone.'],
  'component_dialog_modal.html': ['3.6.1', '对话框 / 模态框', 'Dialog / Modal', '用于需要用户立即关注或确认的短任务。避免嵌套弹窗，并始终提供明确退出路径。', 'Use for short tasks that require immediate attention or confirmation. Avoid nested dialogs and always provide a clear exit.'],
  'component_bottom_sheet.html': ['3.6.2', '底部面板', 'Bottom Sheet', '从屏幕底部呈现补充操作或内容，适合触控场景。保留背景上下文并支持清晰关闭。', 'Presents supporting actions or content from the bottom on touch devices. Preserve context and provide a clear dismiss path.'],
  'component_snackbar_toast.html': ['3.6.3', '消息条 / 轻提示', 'Snackbar / Toast', '反馈已发生的非阻断结果。信息简短、停留时间足够，重要操作不应只存在于轻提示中。', 'Confirms non-blocking outcomes. Keep messages brief and visible long enough; never place essential actions only in a toast.'],
  'component_tooltip.html': ['3.6.4', '工具提示', 'Tooltip', '补充解释图标或陌生控件。不可承载完成任务所必需的信息，并支持键盘与触控访问。', 'Explains icons or unfamiliar controls. Do not place task-critical information in tooltips; support keyboard and touch access.'],
  'component_progress_indicator.html': ['3.6.5', '进度指示器', 'Progress Indicator', '表达等待、加载或任务进度。可测量时显示确定进度，不可测量时使用非确定状态。', 'Communicates waiting, loading, or task progress. Show determinate progress when measurable and indeterminate progress otherwise.'],
};

function renderButtonGuideline(language) {
  const zh = language === 'zh';
  const copy = zh ? {
    title: '按钮', intro: '按钮用于触发即时操作。家电界面的按钮必须在不同观看距离、触控方式和运行状态下保持清晰、稳定且可预期。',
    useTitle: '何时使用', useBody: '用于启动、暂停、确认、保存、取消等明确动作。状态切换使用开关；页面跳转优先使用导航；不可用按钮需解释原因。',
    typeTitle: '按钮类型', typeIntro: '按任务优先级选择类型。单一视区只允许一个主要按钮，避免多个高权重操作竞争。',
    primary: '主要按钮', primaryDesc: '当前任务的唯一主操作，如启动、确认。', secondary: '次要按钮', secondaryDesc: '与主操作并列的辅助动作，如取消、稍后。', outline: '线框按钮', outlineDesc: '用于低频或容器内操作，适合浅色背景。', text: '文字按钮', textDesc: '用于最低层级操作，不承载安全关键动作。', danger: '危险按钮', dangerDesc: '仅用于删除、复位等不可逆或高风险操作。',
    startTitle: '开始按钮', startIntro: '用于启动某个程序、工作流程或设备功能，是海尔品牌 UI 中的高识别度主操作。', startUsageTitle: '使用场景', startUsage: '适用于启动洗涤、烹饪、制冷、清洁等明确程序或功能。不用于页面跳转、选项确认或普通状态切换。', startVisualTitle: '视觉特征', startVisual: '蓝色晕光背景与居中[开始]图标组成。保持图标、光感和圆形边界完整，不改色、不拉伸、不叠加其他图标。', startBehaviorTitle: '交互行为', startBehavior: '点击后立即进入执行中状态，避免重复启动。程序已运行时，应根据任务切换为“暂停”或“停止”，不继续显示开始。', startLabelRule: '语义明确时可单独使用；首次出现、低频功能或存在安全风险时，在按钮下方搭配“开始”或具体动作名称。',
    anatomyTitle: '组成与形状', label: '动词标签', icon: '可选图标', touch: '触控热区', anatomyRule: '统一使用胶囊形按钮。单图标按钮保持等宽等高；图标与文字组合时图标在前，方向性动作可在后。',
    sizeTitle: '尺寸与观看距离', sizeIntro: '按钮分为小、中、大三种尺寸，高度分别为 24px、32px、40px。根据界面密度、观看距离和操作优先级选择。', compact: '小', regular: '中', large: '大', sizeUse: '适用场景', compactUse: '近距屏幕、低频辅助操作', regularUse: '常规触控屏、默认尺寸', largeUse: '远距观看、核心操作', minTarget: '特别说明：视觉高度不等于触控热区。家电触控热区仍不得小于 44 × 44 dp；核心操作按键建议不小于 56 × 56 dp。',
    stateTitle: '交互状态', default: '默认', pressed: '按下', focused: '聚焦', disabled: '禁用', loading: '执行中', success: '完成', stateRule: '触控按下需在 100 ms 内反馈；设备命令超过 300 ms 时进入执行中并阻止重复触发。焦点态同时服务旋钮、遥控器和键盘，不得只靠颜色表达。', semanticTitle: '按钮状态', semanticIntro: '按钮状态分为警告、危险、成功三种，可与主要、次要、线框和文字按钮类型组合使用。状态语义优先于按钮类型。', warning: '警告', dangerState: '危险', successState: '成功',
    iconTitle: '图标按钮', iconRule: '仅当图标语义在该设备场景中高度明确时使用。单图标按钮必须提供可访问名称；首次使用或低频功能应搭配文字。', plus: '添加', power: '启动', more: '更多',
    groupTitle: '组合按钮', groupRule: '同级操作可组合，但最多保留 3 个可见选项。主操作位置跨状态保持稳定；危险操作不得紧邻高频主操作。', start: '启动', pause: '暂停', cancel: '取消', confirm: '确认',
    apiTitle: 'API', apiIntro: '按钮组件的可配置参数。实现时应优先保持规范中的语义、层级和交互反馈。', apiName: '参数', apiDescription: '说明', apiType: '类型', apiDefault: '默认值',
    adaptiveTitle: '跨屏与硬件适配', tft: 'TFT 触控屏', tftDesc: '保留完整标签、图标和交互状态；主操作固定在主要拇指或视线区域。', led: 'LED / 段码屏', ledDesc: '不复制视觉材质。将按钮映射为固定背光标签或实体键，位置与 TFT 主操作保持同侧。', knob: '旋钮 / 遥控器', knobDesc: '提供高对比焦点环；旋转移动焦点，按压确认。焦点不可自动跳走。', narrow: '窄屏 / 条形屏', narrowDesc: '优先保留主操作文字，隐藏装饰图标；需要时使用通栏按钮，不压缩最小热区。',
    safetyTitle: '家电安全约束', safetyItems: ['启动、停止、童锁等关键动作必须保持位置稳定。','高温、高压、门锁等风险动作需要明确后果；必要时二次确认。','紧急停止不可使用仅图标或仅颜色表达，且不得放入溢出菜单。','离线、故障或条件未满足时，禁用按钮旁应显示具体原因与恢复路径。','实体键与屏幕按钮同时存在时，命名、状态和反馈必须一致。'],
    doTitle: '推荐', dontTitle: '避免', doItems: ['使用明确动词：启动、暂停、保存','一个视区只突出一个主要操作','加载时保持按钮宽度和位置稳定'], dontItems: ['使用“确定”“好的”等模糊文案','用禁用状态隐藏业务条件','在运行中允许连续重复触发']
  } : {
    title: 'Buttons', intro: 'Buttons trigger immediate actions. On appliance displays they must remain clear, stable, and predictable across viewing distances, input methods, and operating states.',
    useTitle: 'When to use', useBody: 'Use for explicit actions such as start, pause, confirm, save, or cancel. Use switches for state changes and navigation for moving between pages. Explain why unavailable actions are disabled.',
    typeTitle: 'Button types', typeIntro: 'Choose by task priority. Allow only one primary button in a viewport to avoid competing high-emphasis actions.', primary: 'Primary', primaryDesc: 'The single main action, such as Start or Confirm.', secondary: 'Secondary', secondaryDesc: 'Supporting actions such as Cancel or Later.', outline: 'Outline', outlineDesc: 'Low-frequency or in-container actions on light backgrounds.', text: 'Text', textDesc: 'Lowest emphasis; never for safety-critical actions.', danger: 'Danger', dangerDesc: 'Only for irreversible or high-risk actions.',
    startTitle: 'Start button', startIntro: 'Starts a program, workflow, or appliance function. It is a high-recognition primary action in Haier brand interfaces.', startUsageTitle: 'Use cases', startUsage: 'Use to start an explicit program or function such as washing, cooking, cooling, or cleaning. Do not use it for navigation, option confirmation, or ordinary state changes.', startVisualTitle: 'Visual treatment', startVisual: 'A blue glow background with a centered Start icon. Preserve the icon, lighting, and circular boundary; do not recolor, stretch, or overlay another icon.', startBehaviorTitle: 'Behavior', startBehavior: 'Enter the running state immediately after activation to avoid duplicate starts. Once running, change the control to Pause or Stop when appropriate instead of continuing to show Start.', startLabelRule: 'The symbol may stand alone when its meaning is unambiguous. Add Start or the specific action name below it for first use, infrequent functions, or safety-sensitive contexts.',
    anatomyTitle: 'Anatomy & shape', label: 'Action label', icon: 'Optional icon', touch: 'Touch target', anatomyRule: 'Use pill-shaped buttons consistently. Keep icon-only buttons equal in width and height. Icons precede labels except for directional actions.',
    sizeTitle: 'Size & viewing distance', sizeIntro: 'Buttons use three sizes—small, medium, and large—with heights of 24px, 32px, and 40px. Choose by interface density, viewing distance, and action priority.', compact: 'Small', regular: 'Medium', large: 'Large', sizeUse: 'Use', compactUse: 'Close-range displays, supporting actions', regularUse: 'Regular touchscreens, default size', largeUse: 'Distance viewing, primary actions', minTarget: 'Special note: visual height is not the touch target. Appliance touch targets must still be at least 44 × 44 dp; primary action targets should be at least 56 × 56 dp.',
    stateTitle: 'Interaction states', default: 'Default', pressed: 'Pressed', focused: 'Focused', disabled: 'Disabled', loading: 'Running', success: 'Complete', stateRule: 'Give touch feedback within 100 ms. For commands exceeding 300 ms, enter a running state and prevent duplicate activation. Focus must support knobs, remotes, and keyboards and cannot rely on color alone.', semanticTitle: 'Button status', semanticIntro: 'Warning, danger, and success status can be combined with primary, secondary, outline, and text types. Status meaning takes priority over button type.', warning: 'Warning', dangerState: 'Danger', successState: 'Success',
    iconTitle: 'Icon buttons', iconRule: 'Use only when meaning is highly familiar in context. Icon-only buttons need accessible names; pair unfamiliar or infrequent functions with text.', plus: 'Add', power: 'Start', more: 'More', groupTitle: 'Button groups', groupRule: 'Group peer actions with no more than three visible choices. Keep the primary action stable and separate dangerous actions from frequent ones.', start: 'Start', pause: 'Pause', cancel: 'Cancel', confirm: 'Confirm',
    apiTitle: 'API', apiIntro: 'Configurable properties for the Button component. Implementations should preserve the semantics, hierarchy, and interaction feedback defined in this guideline.', apiName: 'Property', apiDescription: 'Description', apiType: 'Type', apiDefault: 'Default',
    adaptiveTitle: 'Display & hardware adaptation', tft: 'TFT touchscreen', tftDesc: 'Keep full labels, icons, and states; anchor the primary action in the main thumb or sight zone.', led: 'LED / segment display', ledDesc: 'Do not copy visual material. Map actions to fixed backlit labels or physical keys on the same side as TFT.', knob: 'Knob / remote', knobDesc: 'Use a high-contrast focus ring. Rotate to move and press to confirm; focus must not jump automatically.', narrow: 'Narrow / strip display', narrowDesc: 'Keep the action label before decorative icons. Use full-width buttons when needed without shrinking the target.',
    safetyTitle: 'Appliance safety constraints', safetyItems: ['Keep Start, Stop, and Child Lock positions stable.','State consequences for heat, pressure, door lock, or other risks; confirm when necessary.','Never hide Emergency Stop behind an icon, color, or overflow menu.','When offline, faulty, or blocked, explain the reason and recovery next to the disabled action.','Keep labels, state, and feedback aligned across physical and on-screen buttons.'],
    doTitle: 'Do', dontTitle: 'Avoid', doItems: ['Use explicit verbs: Start, Pause, Save','Emphasize only one primary action','Keep button width and position stable while loading'], dontItems: ['Use vague labels such as OK','Hide business conditions behind disabled states','Allow repeated activation while running']
  };
  const apiRows = zh ? [
    ['disabled', '是否禁用按钮。', 'boolean', '—'],
    ['iconOnly', '仅显示图标，按钮宽高相等。', 'boolean', '—'],
    ['long', '按钮宽度随容器自适应。', 'boolean', '—'],
    ['size', '按钮尺寸。', 'mini | small | default | large', 'default'],
    ['status', '按钮的语义状态。', 'default | warning | danger | success', 'default'],
    ['type', '按钮类型：主要、次要、文字、线框或危险。', 'primary | secondary | text | outline | danger', 'primary'],
    ['icon', '设置按钮图标。', 'ReactNode', '—'],
    ['onClick', '点击按钮时触发的回调函数。禁用或执行中状态不得触发。', '(event: MouseEvent) => void', '—'],
    ['style', '设置按钮节点的内联样式。', 'CSSProperties', '—']
  ] : [
    ['disabled', 'Disables the button.', 'boolean', '—'],
    ['iconOnly', 'Shows only an icon with equal width and height.', 'boolean', '—'],
    ['long', 'Makes the button width adapt to its container.', 'boolean', '—'],
    ['size', 'Sets the button size.', 'mini | small | default | large', 'default'],
    ['status', 'Sets the semantic status of the button.', 'default | warning | danger | success', 'default'],
    ['type', 'Sets the button type: primary, secondary, text, outline, or danger.', 'primary | secondary | text | outline | danger', 'primary'],
    ['icon', 'Sets the button icon.', 'ReactNode', '—'],
    ['onClick', 'Callback fired when the button is activated. It must not fire while disabled or running.', '(event: MouseEvent) => void', '—'],
    ['style', 'Sets inline styles on the button element.', 'CSSProperties', '—']
  ];
  const list = (items, tone) => items.map(item => `<li class="flex gap-3 text-sm text-gray-600 leading-6"><span class="${tone === 'good' ? 'text-emerald-500' : 'text-red-400'} font-bold">${tone === 'good' ? '✓' : '×'}</span><span>${item}</span></li>`).join('');
  const segmentShape = 'polygon(12% 0,88% 0,100% 50%,88% 100%,12% 100%,0 50%)';
  const verticalShape = 'polygon(50% 0,100% 12%,100% 88%,50% 100%,0 88%,0 12%)';
  const eightDigit = `<span class="relative block w-5 h-9"><i class="absolute left-[3px] top-0 w-[14px] h-[3px] bg-[#2283E2]" style="clip-path:${segmentShape}"></i><i class="absolute right-0 top-[3px] w-[3px] h-[13px] bg-[#2283E2]" style="clip-path:${verticalShape}"></i><i class="absolute right-0 bottom-[3px] w-[3px] h-[13px] bg-[#2283E2]" style="clip-path:${verticalShape}"></i><i class="absolute left-[3px] bottom-0 w-[14px] h-[3px] bg-[#2283E2]" style="clip-path:${segmentShape}"></i><i class="absolute left-0 bottom-[3px] w-[3px] h-[13px] bg-[#2283E2]" style="clip-path:${verticalShape}"></i><i class="absolute left-0 top-[3px] w-[3px] h-[13px] bg-[#2283E2]" style="clip-path:${verticalShape}"></i><i class="absolute left-[3px] top-[17px] w-[14px] h-[3px] bg-[#2283E2]" style="clip-path:${segmentShape}"></i></span>`;
  const doubleEight = `<div class="flex items-center gap-1" role="img" aria-label="${zh ? '标准双八' : 'Standard double eight'}">${eightDigit}${eightDigit}</div>`;
  const tftScreen = `<div class="w-14 h-9 rounded border-2 border-[#2283E2] bg-blue-50/60" role="img" aria-label="${zh ? 'TFT 横向触控屏' : 'Landscape TFT touchscreen'}"></div>`;
  return `<section class="mb-12"><h1 class="text-4xl md:text-5xl font-bold tracking-tight mb-4 text-gray-900">${copy.title}</h1><p class="text-lg text-gray-500 max-w-3xl leading-relaxed">${copy.intro}</p></section>
  <hr class="border-t border-black/5 mb-8">
  <section class="glass-panel p-6 md:p-10 mb-8"><h2 class="text-2xl font-bold mb-2">${copy.useTitle}</h2><p class="text-sm text-gray-600 leading-6 max-w-3xl">${copy.useBody}</p></section>
  <section class="glass-panel p-6 md:p-10 mb-8"><h2 class="text-2xl font-bold mb-2">${copy.typeTitle}</h2><p class="text-sm text-gray-500 mb-7">${copy.typeIntro}</p><div class="grid md:grid-cols-2 xl:grid-cols-5 gap-4">
    <article class="bg-white/60 border border-gray-200 rounded-xl p-5"><button class="w-full h-12 rounded-full bg-[#2283E2] text-white font-semibold">${copy.primary}</button><p class="text-xs text-gray-500 mt-4 leading-5">${copy.primaryDesc}</p></article>
    <article class="bg-white/60 border border-gray-200 rounded-xl p-5"><button class="w-full h-12 rounded-full bg-[#E5F0FF] text-[#2283E2] font-semibold">${copy.secondary}</button><p class="text-xs text-gray-500 mt-4 leading-5">${copy.secondaryDesc}</p></article>
    <article class="bg-white/60 border border-gray-200 rounded-xl p-5"><button class="w-full h-12 rounded-full border border-[#2283E2] text-[#2283E2] font-semibold">${copy.outline}</button><p class="text-xs text-gray-500 mt-4 leading-5">${copy.outlineDesc}</p></article>
    <article class="bg-white/60 border border-gray-200 rounded-xl p-5"><button class="w-full h-12 rounded-full text-[#2283E2] font-semibold">${copy.text}</button><p class="text-xs text-gray-500 mt-4 leading-5">${copy.textDesc}</p></article>
    <article class="bg-white/60 border border-gray-200 rounded-xl p-5"><button class="w-full h-12 rounded-full bg-red-500 text-white font-semibold">${copy.danger}</button><p class="text-xs text-gray-500 mt-4 leading-5">${copy.dangerDesc}</p></article></div></section>
  <section class="glass-panel p-6 md:p-10 mb-8"><div class="flex flex-col sm:flex-row sm:items-center gap-6 mb-8"><img src="assets/examples/buttons/start-button-light.png" alt="${copy.startTitle}" class="w-36 h-36 shrink-0 object-contain" style="clip-path:circle(38% at 50% 50%)"><div><h2 class="text-2xl font-bold mb-3">${copy.startTitle}</h2><p class="text-sm text-gray-600 leading-6 max-w-3xl">${copy.startIntro}</p></div></div><div class="grid md:grid-cols-3 gap-4"><article class="bg-white/60 border border-gray-200 rounded-xl p-5"><h3 class="font-bold text-sm mb-2">${copy.startUsageTitle}</h3><p class="text-xs text-gray-500 leading-5">${copy.startUsage}</p></article><article class="bg-white/60 border border-gray-200 rounded-xl p-5"><h3 class="font-bold text-sm mb-2">${copy.startVisualTitle}</h3><p class="text-xs text-gray-500 leading-5">${copy.startVisual}</p></article><article class="bg-white/60 border border-gray-200 rounded-xl p-5"><h3 class="font-bold text-sm mb-2">${copy.startBehaviorTitle}</h3><p class="text-xs text-gray-500 leading-5">${copy.startBehavior}</p></article></div><p class="mt-5 p-4 rounded-xl bg-blue-50 text-sm text-[#2283E2] leading-6">${copy.startLabelRule}</p></section>
  <section class="glass-panel p-6 md:p-10 mb-8"><h2 class="text-2xl font-bold mb-2">${copy.sizeTitle}</h2><p class="text-sm text-gray-600 mb-6">${copy.sizeIntro}</p><div class="overflow-x-auto"><table class="w-full text-sm"><thead><tr class="text-left text-gray-500 border-b"><th class="py-3">Size</th><th>Height</th><th>Example</th><th>${copy.sizeUse}</th></tr></thead><tbody><tr class="h-20 border-b"><td class="py-6 font-semibold">${copy.compact}</td><td>24px</td><td><button class="h-6 px-4 rounded-full bg-[#2283E2] text-white text-xs font-semibold">${copy.confirm}</button></td><td class="text-gray-600">${copy.compactUse}</td></tr><tr class="h-20 border-b"><td class="py-6 font-semibold">${copy.regular}</td><td>32px</td><td><button class="h-8 min-w-[96px] px-6 rounded-full bg-[#2283E2] text-white text-sm font-semibold">${copy.confirm}</button></td><td class="text-gray-600">${copy.regularUse}</td></tr><tr class="h-20"><td class="py-6 font-semibold">${copy.large}</td><td>40px</td><td><button class="h-10 min-w-[120px] px-8 rounded-full bg-[#2283E2] text-white text-base font-semibold">${copy.confirm}</button></td><td class="text-gray-600">${copy.largeUse}</td></tr></tbody></table></div><p class="mt-6 p-4 rounded-xl bg-blue-50 text-sm text-[#2283E2] leading-6">${copy.minTarget}</p></section>
  <section class="glass-panel p-6 md:p-10 mb-8"><h2 class="text-2xl font-bold mb-6">${copy.stateTitle}</h2><div class="flex flex-wrap gap-8 mb-6">
    <div class="flex justify-center"><button class="h-10 min-w-[120px] px-8 rounded-full bg-[#2283E2] text-white font-semibold">${copy.default}</button></div><div class="flex justify-center"><button class="h-10 min-w-[120px] px-8 rounded-full bg-[#0969C3] text-white font-semibold scale-[.97]">${copy.pressed}</button></div><div class="flex justify-center"><button disabled class="h-10 min-w-[120px] px-8 rounded-full bg-gray-200 text-gray-400 font-semibold cursor-not-allowed">${copy.disabled}</button></div><div class="flex justify-center"><button class="h-10 min-w-[120px] px-8 rounded-full bg-blue-100 text-[#2283E2] font-semibold">${copy.loading}</button></div><div class="flex justify-center"><button class="h-10 min-w-[120px] px-8 rounded-full bg-emerald-500 text-white font-semibold">✓ ${copy.success}</button></div></div><p class="text-sm text-gray-600 leading-6">${copy.stateRule}</p></section>
  <section class="glass-panel p-6 md:p-10 mb-8"><h2 class="text-2xl font-bold mb-2">${copy.semanticTitle}</h2><p class="text-sm text-gray-500 mb-7">${copy.semanticIntro}</p><div class="space-y-6">
    <div><div class="flex flex-wrap gap-8"><button class="w-[120px] h-10 rounded-full bg-amber-500 text-white font-semibold">${copy.warning}</button><button class="w-[120px] h-10 rounded-full bg-amber-50 text-amber-600 font-semibold">${copy.warning}</button><button class="w-[120px] h-10 rounded-full border border-amber-500 text-amber-600 font-semibold">${copy.warning}</button><button class="w-[120px] h-10 rounded-full text-amber-600 font-semibold">${copy.warning}</button></div></div>
    <div><div class="flex flex-wrap gap-8"><button class="w-[120px] h-10 rounded-full bg-red-500 text-white font-semibold">${copy.dangerState}</button><button class="w-[120px] h-10 rounded-full bg-red-50 text-red-600 font-semibold">${copy.dangerState}</button><button class="w-[120px] h-10 rounded-full border border-red-500 text-red-600 font-semibold">${copy.dangerState}</button><button class="w-[120px] h-10 rounded-full text-red-600 font-semibold">${copy.dangerState}</button></div></div>
    <div><div class="flex flex-wrap gap-8"><button class="w-[120px] h-10 rounded-full bg-emerald-500 text-white font-semibold">${copy.successState}</button><button class="w-[120px] h-10 rounded-full bg-emerald-50 text-emerald-600 font-semibold">${copy.successState}</button><button class="w-[120px] h-10 rounded-full border border-emerald-500 text-emerald-600 font-semibold">${copy.successState}</button><button class="w-[120px] h-10 rounded-full text-emerald-600 font-semibold">${copy.successState}</button></div></div>
  </div></section>
  <section class="grid lg:grid-cols-2 gap-8 mb-8"><article class="glass-panel p-6 md:p-10"><h2 class="text-2xl font-bold mb-2">${copy.iconTitle}</h2><p class="text-sm text-gray-500 leading-6 mb-6">${copy.iconRule}</p><div class="flex flex-wrap gap-5"><div class="text-center"><button aria-label="${copy.plus}" class="w-14 h-14 rounded-full bg-[#2283E2] flex items-center justify-center"><img src="assets/icons/button-add.png" alt="" class="w-7 h-7 object-contain"></button><p class="text-xs text-gray-500 mt-2">${copy.plus}</p></div><div class="text-center"><button aria-label="${copy.power}" class="w-14 h-14 rounded-full bg-[#2283E2] flex items-center justify-center"><img src="assets/icons/button-start.png" alt="" class="w-7 h-7 object-contain"></button><p class="text-xs text-gray-500 mt-2">${copy.power}</p></div><div class="text-center"><button aria-label="${copy.more}" class="w-14 h-14 rounded-full bg-[#2283E2] flex items-center justify-center"><img src="assets/icons/button-more.png" alt="" class="w-7 h-7 object-contain"></button><p class="text-xs text-gray-500 mt-2">${copy.more}</p></div></div></article>
  <article class="glass-panel p-6 md:p-10"><h2 class="text-2xl font-bold mb-2">${copy.groupTitle}</h2><p class="text-sm text-gray-500 leading-6 mb-6">${copy.groupRule}</p><div class="inline-flex gap-2"><button class="h-10 min-w-[120px] px-8 rounded-full border border-[#2283E2] text-[#2283E2] font-semibold">${copy.cancel}</button><button class="h-10 min-w-[120px] px-8 rounded-full bg-[#2283E2] text-white font-semibold">${copy.confirm}</button></div></article></section>
  <section class="glass-panel p-6 md:p-10 mb-8"><h2 class="text-2xl font-bold mb-2">${copy.apiTitle}</h2><p class="text-sm text-gray-500 leading-6 mb-7 max-w-3xl">${copy.apiIntro}</p><div class="overflow-x-auto rounded-2xl border border-white/80 bg-white/45"><table class="w-full min-w-[760px] text-left"><thead><tr class="border-b border-gray-200/80 text-xs text-gray-500"><th class="px-5 py-4 font-semibold w-[18%]">${copy.apiName}</th><th class="px-5 py-4 font-semibold w-[38%]">${copy.apiDescription}</th><th class="px-5 py-4 font-semibold w-[30%]">${copy.apiType}</th><th class="px-5 py-4 font-semibold w-[14%]">${copy.apiDefault}</th></tr></thead><tbody>${apiRows.map(([name,description,type,defaultValue])=>`<tr class="border-b border-gray-200/70 last:border-0 hover:bg-white/55 transition-colors"><td class="px-5 py-4 align-top"><code class="inline-flex rounded-lg bg-[#E5F0FF] px-2.5 py-1 text-xs font-semibold text-[#2283E2]">${name}</code></td><td class="px-5 py-4 align-top text-sm text-gray-600 leading-6">${description}</td><td class="px-5 py-4 align-top"><code class="text-xs text-gray-600 break-words">${type}</code></td><td class="px-5 py-4 align-top"><code class="text-xs text-gray-600">${defaultValue}</code></td></tr>`).join('')}</tbody></table></div></section>
  <section class="glass-panel p-6 md:p-10 mb-8"><h2 class="text-2xl font-bold mb-6">${copy.adaptiveTitle}</h2><div class="grid md:grid-cols-2 xl:grid-cols-4 gap-5">${[[copy.tft,copy.tftDesc,tftScreen],[copy.led,copy.ledDesc,doubleEight],[copy.knob,copy.knobDesc,'◉'],[copy.narrow,copy.narrowDesc,'▬']].map(([t,d,g])=>`<article class="bg-white/60 border border-gray-200 rounded-xl p-5"><div class="h-16 flex items-center text-2xl font-bold text-[#2283E2]">${g}</div><h3 class="font-bold mb-2">${t}</h3><p class="text-xs text-gray-500 leading-5">${d}</p></article>`).join('')}</div></section>
  <section class="glass-panel p-6 md:p-10 mb-8"><h2 class="text-2xl font-bold mb-6">${copy.safetyTitle}</h2><ul class="grid md:grid-cols-2 gap-x-8 gap-y-3">${list(copy.safetyItems,'good')}</ul></section>
  <section class="grid md:grid-cols-2 gap-8 mb-10"><article class="bg-emerald-50/80 border border-emerald-100 rounded-3xl p-6 md:p-8"><h2 class="text-xl font-bold text-emerald-800 mb-5">${copy.doTitle}</h2><ul class="space-y-3">${list(copy.doItems,'good')}</ul></article><article class="bg-red-50/80 border border-red-100 rounded-3xl p-6 md:p-8"><h2 class="text-xl font-bold text-red-800 mb-5">${copy.dontTitle}</h2><ul class="space-y-3">${list(copy.dontItems,'bad')}</ul></article></section>`;
}

function renderSwitchGuideline(language) {
  const zh = language === 'zh';
  const copy = zh ? {
    title: '开关', intro: '开关用于控制一个设置或设备能力的开启与关闭，操作后立即生效。标签描述被控制的对象，不重复“开 / 关”。',
    useTitle: '何时使用', useBody: '用于 Wi-Fi、童锁、提示音等独立二元设置。需要提交后才生效时使用复选框；用于启动一次性任务时使用按钮；多项互斥选择使用单选按钮。',
    typeTitle: '类型与尺寸', typeIntro: '仅使用圆形滑块的胶囊形开关。提供默认与小型两组，不使用方形滑块、矩形轨道或图标装饰。', defaultSize: '默认', smallSize: '小型', defaultUse: '常规触控界面与独立设置项', smallUse: '高密度列表与近距离屏幕', track: '轨道', thumb: '滑块', touch: '触控热区',
    dimension: '规格', visual: '视觉尺寸', thumbSize: '滑块尺寸', target: '最小热区', usage: '适用场景',
    anatomyTitle: '组成与布局', anatomyRule: '标签置于开关左侧，开关与标签整体作为同一交互项。开关靠列表末端对齐；标签过长时换行，但不得挤压开关。',
    statesTitle: '状态', statesIntro: '所有尺寸使用同一套状态语义。点击示例可切换开启与关闭。', off: '关闭', on: '开启', disabledOff: '禁用关闭', disabledOn: '禁用开启', loading: '处理中', focus: '键盘聚焦',
    behaviorTitle: '交互与反馈', behaviorItems: ['点击开关或其标签即可切换；触控热区不得小于 44 × 44 dp。','操作后立即更新视觉状态，并同步设备真实状态。','设备响应超过 300 ms 时进入处理中状态，锁定重复操作；失败后回退并说明原因。','支持 Tab 聚焦与 Space / Enter 切换；焦点环必须清晰可见。','不要仅用颜色表达状态；标签、位置与辅助技术需共同传达当前值。'],
    labelTitle: '标签规则', labelItems: ['使用名词或名词短语，如“提示音”“童锁”。','开启与关闭的结果应可预测；若会触发高风险行为，应增加确认。','不要把“开 / 关”写进标签，也不要用开关执行“启动”“保存”等一次性动作。'],
    apiTitle: 'API', apiIntro: '实现时优先保持即时生效、状态同步和无障碍语义。', apiName: '参数', apiDesc: '说明', apiType: '类型', apiDefault: '默认值',
    doTitle: '推荐', dontTitle: '避免', doItems: ['标签描述被控制的设置','切换后立即反馈真实状态','同一列表内右对齐开关'], dontItems: ['使用方形或矩形开关形态','在滑块或轨道内放置图标','用开关提交表单或启动任务']
  } : {
    title: 'Switch', intro: 'A switch controls whether a setting or device capability is on or off and takes effect immediately. Its label names the controlled setting instead of repeating “on / off”.',
    useTitle: 'When to use', useBody: 'Use for independent binary settings such as Wi-Fi, Child lock, or Sounds. Use a checkbox when changes require submission, a button for one-time actions, and radio buttons for mutually exclusive choices.',
    typeTitle: 'Types & sizes', typeIntro: 'Use only pill tracks with circular thumbs. Two groups are available: default and small. Do not use square thumbs, rectangular tracks, or icon decoration.', defaultSize: 'Default', smallSize: 'Small', defaultUse: 'Regular touch UI and standalone settings', smallUse: 'Dense lists and close-range displays', track: 'Track', thumb: 'Thumb', touch: 'Touch target',
    dimension: 'Size', visual: 'Visual size', thumbSize: 'Thumb', target: 'Minimum target', usage: 'Use',
    anatomyTitle: 'Anatomy & layout', anatomyRule: 'Place the label before the switch and make the whole row interactive. Align switches to the trailing edge. Long labels may wrap but must not squeeze the switch.',
    statesTitle: 'States', statesIntro: 'Both sizes share the same state semantics. Activate the examples to toggle them.', off: 'Off', on: 'On', disabledOff: 'Disabled off', disabledOn: 'Disabled on', loading: 'Processing', focus: 'Keyboard focus',
    behaviorTitle: 'Interaction & feedback', behaviorItems: ['Toggle from either the switch or its label; keep the touch target at least 44 × 44 dp.','Update the visual state immediately and synchronize it with the actual device state.','If the device takes over 300 ms, show processing and block repeated input; on failure, revert and explain why.','Support Tab focus and Space / Enter toggling with a clearly visible focus ring.','Do not rely on color alone; label, position, and assistive semantics must convey the value.'],
    labelTitle: 'Labeling', labelItems: ['Use a noun or noun phrase such as “Sounds” or “Child lock”.','Make the result of each state predictable; confirm separately for high-risk consequences.','Do not include “on / off” in the label or use a switch for Start, Save, or other one-time actions.'],
    apiTitle: 'API', apiIntro: 'Implementations should preserve immediate effect, state synchronization, and accessible semantics.', apiName: 'Property', apiDesc: 'Description', apiType: 'Type', apiDefault: 'Default',
    doTitle: 'Do', dontTitle: 'Avoid', doItems: ['Name the controlled setting','Reflect the real state immediately','Align switches at the list edge'], dontItems: ['Use square or rectangular switch forms','Place icons inside the thumb or track','Submit forms or start tasks with a switch']
  };
  const switchControl = (checked, size = 'default', disabled = false, extra = '') => {
    const small = size === 'small';
    return `<button type="button" role="switch" aria-checked="${checked}" ${disabled ? 'disabled' : ''} data-guideline-switch class="relative shrink-0 ${small ? 'w-7 h-4' : 'w-10 h-6'} rounded-full transition-colors duration-200 ${checked ? 'bg-[#2283E2]' : 'bg-gray-300'} ${disabled ? 'opacity-45 cursor-not-allowed' : 'cursor-pointer'} ${extra}"><span class="absolute top-1/2 -translate-y-1/2 rounded-full bg-white shadow-sm transition-all duration-200 ${small ? 'w-3 h-3' : 'w-4 h-4'} ${checked ? (small ? 'left-[14px]' : 'left-[22px]') : (small ? 'left-[2px]' : 'left-[3px]')}"></span></button>`;
  };
  const list = (items, good = true) => items.map(item => `<li class="flex gap-3 text-sm text-gray-600 leading-6"><span class="${good ? 'text-emerald-500' : 'text-red-400'} font-bold">${good ? '✓' : '×'}</span><span>${item}</span></li>`).join('');
  const apiRows = zh ? [
    ['checked', '受控的开启状态。', 'boolean', '—'], ['defaultChecked', '非受控模式的初始状态。', 'boolean', 'false'], ['disabled', '禁用交互并保留当前状态。', 'boolean', 'false'], ['loading', '表示状态正在同步，并阻止重复切换。', 'boolean', 'false'], ['size', '开关尺寸，仅默认与小型。', "'default' | 'small'", "'default'"], ['onChange', '状态改变时触发；应同步设备真实状态。', '(checked: boolean) => void', '—']
  ] : [
    ['checked', 'Controlled on state.', 'boolean', '—'], ['defaultChecked', 'Initial state when uncontrolled.', 'boolean', 'false'], ['disabled', 'Blocks interaction while preserving the current value.', 'boolean', 'false'], ['loading', 'Shows synchronization and blocks repeated toggles.', 'boolean', 'false'], ['size', 'Switch size; default and small only.', "'default' | 'small'", "'default'"], ['onChange', 'Fires on change; synchronize the actual device state.', '(checked: boolean) => void', '—']
  ];
  return `<section class="mb-12"><h1 class="text-4xl md:text-5xl font-bold tracking-tight mb-4 text-gray-900">${copy.title}</h1><p class="text-lg text-gray-500 max-w-3xl leading-relaxed">${copy.intro}</p></section>
  <hr class="border-t border-black/5 mb-8">
  <section class="glass-panel p-6 md:p-10 mb-8"><h2 class="text-2xl font-bold mb-2">${copy.useTitle}</h2><p class="text-sm text-gray-600 leading-6 max-w-3xl">${copy.useBody}</p></section>
  <section class="glass-panel p-6 md:p-10 mb-8"><h2 class="text-2xl font-bold mb-2">${copy.typeTitle}</h2><p class="text-sm text-gray-500 mb-7">${copy.typeIntro}</p><div class="grid md:grid-cols-2 gap-5 mb-8">
    <article class="bg-white/60 border border-gray-200 rounded-xl p-6"><div class="h-16 flex items-center gap-8">${switchControl(false)}${switchControl(true)}</div><h3 class="font-bold">${copy.defaultSize}</h3><p class="text-xs text-gray-500 mt-2">40 × 24 px · ${copy.defaultUse}</p></article>
    <article class="bg-white/60 border border-gray-200 rounded-xl p-6"><div class="h-16 flex items-center gap-8">${switchControl(false,'small')}${switchControl(true,'small')}</div><h3 class="font-bold">${copy.smallSize}</h3><p class="text-xs text-gray-500 mt-2">28 × 16 px · ${copy.smallUse}</p></article></div>
    <div class="overflow-x-auto"><table class="w-full min-w-[640px] text-sm"><thead><tr class="text-left text-gray-500 border-b"><th class="py-3">${copy.dimension}</th><th>${copy.visual}</th><th>${copy.thumbSize}</th><th>${copy.target}</th><th>${copy.usage}</th></tr></thead><tbody><tr class="border-b"><td class="py-4 font-semibold">${copy.defaultSize}</td><td>40 × 24 px</td><td>16 px</td><td>44 × 44 dp</td><td class="text-gray-600">${copy.defaultUse}</td></tr><tr><td class="py-4 font-semibold">${copy.smallSize}</td><td>28 × 16 px</td><td>12 px</td><td>44 × 44 dp</td><td class="text-gray-600">${copy.smallUse}</td></tr></tbody></table></div></section>
  <section class="glass-panel p-6 md:p-10 mb-8"><h2 class="text-2xl font-bold mb-2">${copy.anatomyTitle}</h2><p class="text-sm text-gray-500 leading-6 mb-7 max-w-3xl">${copy.anatomyRule}</p><div class="max-w-2xl rounded-2xl border border-gray-200 bg-white/65 p-5"><div class="flex items-center justify-between min-h-[52px] gap-6"><div><p class="font-semibold">${zh ? '提示音' : 'Sounds'}</p><p class="text-xs text-gray-500 mt-1">${zh ? '操作完成时播放声音' : 'Play a sound when an action finishes'}</p></div>${switchControl(true)}</div></div></section>
  <section class="glass-panel p-6 md:p-10 mb-8"><h2 class="text-2xl font-bold mb-2">${copy.statesTitle}</h2><p class="text-sm text-gray-500 mb-7">${copy.statesIntro}</p><div class="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
    ${[[copy.off,switchControl(false)],[copy.on,switchControl(true)],[copy.disabledOff,switchControl(false,'default',true)],[copy.disabledOn,switchControl(true,'default',true)],[copy.loading,switchControl(true,'default',true,'animate-pulse')],[copy.focus,switchControl(true,'default',false,'ring-2 ring-[#2283E2]/35 ring-offset-2')]].map(([label,control])=>`<article class="bg-white/60 border border-gray-200 rounded-xl p-5"><div class="h-11 flex items-center">${control}</div><p class="text-xs text-gray-500 mt-2">${label}</p></article>`).join('')}</div></section>
  <section class="grid lg:grid-cols-2 gap-8 mb-8"><article class="glass-panel p-6 md:p-8"><h2 class="text-xl font-bold mb-5">${copy.behaviorTitle}</h2><ul class="space-y-3">${list(copy.behaviorItems)}</ul></article><article class="glass-panel p-6 md:p-8"><h2 class="text-xl font-bold mb-5">${copy.labelTitle}</h2><ul class="space-y-3">${list(copy.labelItems)}</ul></article></section>
  <section class="glass-panel p-6 md:p-10 mb-8"><h2 class="text-2xl font-bold mb-2">${copy.apiTitle}</h2><p class="text-sm text-gray-500 mb-7">${copy.apiIntro}</p><div class="overflow-x-auto rounded-2xl border border-white/80 bg-white/45"><table class="w-full min-w-[760px] text-left"><thead><tr class="border-b border-gray-200/80 text-xs text-gray-500"><th class="px-5 py-4">${copy.apiName}</th><th class="px-5 py-4">${copy.apiDesc}</th><th class="px-5 py-4">${copy.apiType}</th><th class="px-5 py-4">${copy.apiDefault}</th></tr></thead><tbody>${apiRows.map(row=>`<tr class="border-b border-gray-200/70 last:border-0"><td class="px-5 py-4"><code class="rounded-lg bg-[#E5F0FF] px-2.5 py-1 text-xs font-semibold text-[#2283E2]">${row[0]}</code></td><td class="px-5 py-4 text-sm text-gray-600">${row[1]}</td><td class="px-5 py-4"><code class="text-xs text-gray-600">${row[2]}</code></td><td class="px-5 py-4"><code class="text-xs text-gray-600">${row[3]}</code></td></tr>`).join('')}</tbody></table></div></section>
  <section class="grid md:grid-cols-2 gap-8 mb-10"><article class="bg-emerald-50/80 border border-emerald-100 rounded-3xl p-6 md:p-8"><h2 class="text-xl font-bold text-emerald-800 mb-5">${copy.doTitle}</h2><ul class="space-y-3">${list(copy.doItems)}</ul></article><article class="bg-red-50/80 border border-red-100 rounded-3xl p-6 md:p-8"><h2 class="text-xl font-bold text-red-800 mb-5">${copy.dontTitle}</h2><ul class="space-y-3">${list(copy.dontItems,false)}</ul></article></section>`;
}

function initSwitchExamples(root) {
  root.querySelectorAll('[data-guideline-switch]:not([disabled])').forEach(control => control.addEventListener('click', () => {
    const checked = control.getAttribute('aria-checked') === 'true';
    const thumb = control.querySelector('span');
    const small = control.classList.contains('w-7');
    control.setAttribute('aria-checked', String(!checked));
    control.classList.toggle('bg-[#2283E2]', !checked);
    control.classList.toggle('bg-gray-300', checked);
    thumb.classList.toggle(small ? 'left-[14px]' : 'left-[22px]', !checked);
    thumb.classList.toggle(small ? 'left-[2px]' : 'left-[3px]', checked);
  }));
}

(function renderComponentPage() {
  const file = window.location.pathname.split('/').pop();
  const item = COMPONENT_PAGES[file];
  const root = document.getElementById('component-page');
  if (!item || !root) return;
  const [number, zh, en, zhDescription, enDescription] = item;
  const language = localStorage.getItem('haier-guideline-language') || 'zh';
  const text = language === 'zh'
    ? { title: zh, description: zhDescription, overview: '基础规范', status: '状态规范', usage: '使用原则', anatomy: '组成结构', statusText: '默认、悬停、聚焦、按下、禁用与错误状态需使用一致的视觉语言，并满足键盘与触控可达性。', usageText: '先确认组件是否匹配用户任务，再定义内容、行为与边界条件。避免用视觉变体修补错误的信息结构。', anatomyText: '名称、内容区域、交互热区与反馈层应保持职责清晰；跨设备适配时优先保持语义和操作顺序。' }
    : { title: en, description: enDescription, overview: 'Foundation', status: 'States', usage: 'Usage', anatomy: 'Anatomy', statusText: 'Use a consistent visual language for default, hover, focus, pressed, disabled, and error states, with keyboard and touch accessibility.', usageText: 'Confirm the component matches the user task before defining content, behavior, and boundaries. Do not use visual variants to patch weak information structure.', anatomyText: 'Keep labels, content, touch targets, and feedback layers distinct. Preserve meaning and action order when adapting across devices.' };
  document.title = `Haier Design | ${text.title}`;
  if (file === 'component_buttons.html') {
    root.innerHTML = renderButtonGuideline(language);
    return;
  }
  if (file === 'component_switch.html') {
    root.innerHTML = renderSwitchGuideline(language);
    initSwitchExamples(root);
    return;
  }
  root.innerHTML = `
    <section class="mb-12">
      <h1 class="text-4xl md:text-5xl font-bold tracking-tight mb-4 text-gray-900">${text.title}</h1>
      <p class="text-lg text-gray-500 max-w-3xl leading-relaxed">${text.description}</p>
    </section>
    <hr class="border-t border-black/5 mb-8">
    <section class="glass-panel p-6 md:p-10 mb-10">
      <div class="mb-6"><h2 class="text-2xl font-bold text-gray-900 mb-2">${text.overview}</h2><p class="text-sm text-gray-500">${en}</p></div>
      <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <article class="bg-white/60 rounded-xl p-5 border border-gray-200"><span class="text-xs font-bold text-blue-600">01</span><h3 class="font-bold text-gray-800 mt-4 mb-2">${text.usage}</h3><p class="text-sm text-gray-600 leading-6">${text.usageText}</p></article>
        <article class="bg-white/60 rounded-xl p-5 border border-gray-200"><span class="text-xs font-bold text-blue-600">02</span><h3 class="font-bold text-gray-800 mt-4 mb-2">${text.anatomy}</h3><p class="text-sm text-gray-600 leading-6">${text.anatomyText}</p></article>
        <article class="bg-white/60 rounded-xl p-5 border border-gray-200"><span class="text-xs font-bold text-blue-600">03</span><h3 class="font-bold text-gray-800 mt-4 mb-2">${text.status}</h3><p class="text-sm text-gray-600 leading-6">${text.statusText}</p></article>
      </div>
    </section>`;
})();
